import type {Metadata} from "next";
import "../globals.css";
import {SidebarProvider} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/admin/app-sidebar";
import {cookies} from "next/headers"
import {ThemeProvider} from "next-themes";
import NavBar from "@/components/admin/Navbar";
// import StoreProvider from "@/components/ui/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="bg-khotixs-background-white dark:bg-khotixs-background-dark  ">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider defaultOpen={defaultOpen}>

                <AppSidebar/>
                <main className="w-full overflow-x-hidden">

                    <section className="z-40 top-0 sticky w-full flex justify-between h-auto">
                        <NavBar/>
                    </section>

                    <section className="dark:bg-gray-500 dark:backdrop-blur dark:bg-opacity-5 px-20 py-10 ">
                        {children}
                    </section>
                </main>


            </SidebarProvider>

        </ThemeProvider>

        </body>
        </html>
    );
}